<html lang="en">
<meta charset="utf-8">
<head>
<title>POWER BI </title>
</head>
<body>
<H1>THIS IS WEBPAGE FOR POWERBI SECURE EMBED POST<H1>
<H1>USERS ARE SUPPOSE TO LOG IN TO VIEW THIS CONTENT<H1>
<iframe width="1140" height="541.25" src="https://app.powerbi.com/reportEmbed?reportId=1cad20a1-07d9-43f9-832a-fb52d27b9f37&autoAuth=true&ctid=6d09a68c-8cf0-401b-ab64-a95022dfe824&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXNvdXRoLWVhc3QtYXNpYS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
</body>
</html>